env:
  es2021: true
  node: true
extends:
  - '@sapphire'
parserOptions:
  warnOnUnsupportedTypeScriptVersion: false
plugins:
  - '@typescript-eslint'
rules:
  no-console: off
  no-lonely-if: warn
  quotes: [warn, 'single']